FROM debian:12-slim

RUN apt update && apt install -y build-essential
RUN apt install -y nano libreadline-dev

COPY ./scripts/start.sh /start/start.sh
RUN chmod +x /start/start.sh

WORKDIR /src

CMD ["/start/start.sh"]
