server {
	listen       80;
	server_name  localhost;

	charset utf-8;
	access_log  /var/log/nginx/app.access.log main;

	underscores_in_headers on;

	location / {
        root   /build/front/dist;
        index  index.html;
		expires 60d;
		add_header Cache-Control "public, max-age=2592000, immutable";
		try_files $uri $uri/ /index.html;
    }

    # Proxy para o WebSocket do Backend Elixir (BFF)
    location /ws {
        proxy_pass http://backend:4000/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Proxy para o Endpoint de Token do Backend Elixir (BFF)
    location /token {
        proxy_pass http://backend:4000/token;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
