FROM debian:12

RUN apt update && apt install -y build-essential
RUN apt install -y zsh curl gnupg git nano sqlite3 libsqlite3-dev libreadline-dev
RUN apt install -y libssl-dev libncurses5-dev automake autoconf libxml2-utils unzip
RUN rm -rf /var/lib/apt/lists/*

ENV MISE_INSTALL_PATH=/usr/local/bin/mise
RUN curl https://mise.jdx.dev/install.sh | sh
ENV MISE_DATA_DIR=/opt/mise
ENV PATH="/opt/mise/shims:$PATH"
ENV ELIXIR_ERL_OPTIONS="+fnu"

RUN mise use --global erlang@latest elixir@latest

COPY ./scripts/start.sh /start/start.sh
RUN chmod +x /start/start.sh

RUN apt update && apt install -y sudo && \
    useradd -m -s /bin/zsh user

WORKDIR /src

# USER user

CMD ["/start/start.sh"]
